import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  String _languageCode = 'en';

  String get languageCode => _languageCode;
  bool get isArabic => _languageCode == 'ar';

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _languageCode = prefs.getString('language_code') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    if (_languageCode == code) return;
    
    _languageCode = code;
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', code);
    
    notifyListeners();
  }

  String translate(String key) {
    final translations = {
      'en': {
        // Onboarding
        'welcomeToMunir': 'Welcome to Munir',
        'smartAssistance': 'Smart Assistance for You',
        'aiCompanion': 'Your AI-powered companion for easier daily life.',
        'readTextRecognize': 'Read text, recognize faces, and get real-time feedback.',
        'tapToContinue': 'Tap anywhere to continue',
        
        // Welcome Screen
        'welcomeToJourney': 'Welcome to your new journey',
        'createAccount': 'Create Account',
        'login': 'Login',
        
        // Login Screen
        'welcomeBack': 'Welcome Back',
        'loginToContinue': 'Log in to continue your journey',
        'emailAddress': 'Email Address',
        'password': 'Password',
        'rememberMe': 'Remember me',
        'forgotPassword': 'Forgot Password?',
        'or': 'OR',
        'continueWithGoogle': 'Continue with Google',
        'dontHaveAccount': "Don't have an account? ",
        'signUp': 'Sign Up',
        'logIn': 'Log In',
        
        // Signup Screen
        'joinUs': 'Join us and start your journey',
        'name': 'Name',
        'mobileNumber': 'Mobile Number (05XXXXXXXX)',
        'confirmPassword': 'Confirm Password',
        'passwordRequirements': 'Password Requirements:',
        'atLeast8Chars': 'At least 8 characters',
        'oneUppercase': 'Uppercase letter (A-Z)',
        'oneLowercase': 'Lowercase letter (a-z)',
        'oneNumber': 'Number (0-9)',
        'oneSpecialChar': 'Special character',
        'passwordStrength': 'Password Strength',
        'alreadyHaveAccount': 'Already have an account? ',
        
        // Email Verification
        'checkYourEmail': 'Check Your Email',
        'emailVerified': 'Email Verified!',
        'redirectingToHome': 'Redirecting to home...',
        'weSentEmail': 'We sent an email to',
        'important': 'IMPORTANT!',
        'checkSpam': 'Check your SPAM/JUNK folder!',
        'nextSteps': 'Next Steps',
        'resendEmail': 'Resend Verification Email',
        'resendIn': 'Resend in',
        'seconds': 'seconds',
        'backToLogin': 'Back to Login',

        // Settings Page
        'settings': 'Settings',
        'managePreferences': 'Manage your preferences',
        'accountInfo': 'Account Info',
        'editPersonalInfo': 'Edit personal info or delete your account',
        'deviceAlerts': 'Device & Alerts',
        'setupConnections': 'Set up connections and notifications',
        'changePassword': 'Change Password',
        'managePassword': 'Manage your password',
        'logout': 'Logout',
        'signOut': 'Sign out of your account',
        'logoutConfirm': 'Are you sure you want to log out from your account?',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'logoutSuccess': 'Logout successfully',
        'logoutFailed': 'Failed to logout. Please try again.',
        'goingBack': 'Going back',
        'home': 'Home',
        'reminders': 'Reminders',
        'contacts': 'Contacts',
        'emergency': 'Emergency SOS',
        'alreadyOnSettings': 'You are already on Settings page',

        // HomePage
        'faceRecognition': 'Face Recognition',
        'identifyPeopleInstantly': 'Identify people instantly',
        'textReading': 'Text Reading',
        'readTextAloud': 'Read text aloud',
        'currencyRecognition': 'Currency Recognition',
        'recognizeCurrencyInstantly': 'Recognize currency instantly',
        'colorIdentification': 'Color Identification',
        'identifyColorsAround': 'Identify colors around you',
        'profile': 'Profile',
        'managePersonalInfo': 'Manage your personal information',
        'alreadyOnHomepage': 'You are already on homepage',

        // Account Info Page
        'manageAccountSettings': 'Manage your account settings',
        'personalInformation': 'Personal Information',
        'editAccountInfo': 'Edit your account information',
        'deleteMyAccount': 'Delete My Account',
        'permanentlyDelete': 'Permanently delete your account',
        'deleteAccount': 'Delete Account',
        'deleteAccountConfirm': 'Are you sure you want to delete your account? This action cannot be undone',
        'deletionCancelled': 'Deletion cancelled',
        'noUserSignedIn': 'No user is currently signed in',
        'emailNotFound': 'Email not found. Please log in again.',
        'confirmYourPassword': 'Confirm Your Password',
        'enterPasswordToContinue': 'Please enter your password to continue.',
        'enterYourPassword': 'Enter your password',
        'passwordRequired': 'Password is required',
        'invalidPassword': 'Invalid password. Please try again',
        'pleaseWait': 'Please wait...',
        'reauthCancelled': 'Reauthentication cancelled',
        'networkTimeout': 'Network timeout while verifying password.',
        'authError': 'Authentication error.',
        'unexpectedError': 'Unexpected error during verification.',
        'accountDeletedSuccess': 'Account deleted successfully',
        'redirectingToSignup': 'Account deleted successfully. Redirecting to sign up',

        // AddPersonPage
        'addNewPerson': 'Add New Person',
        'enterName': 'Enter name',
        'photo': 'Photo',
        'tapToCaptureFaceRotation': 'Tap to capture face rotation',
        'frontLeftRightUpDown': 'Front, Left, Right, Up, Down',
        'rotationPhotosCaptured': 'rotation photos captured',
        'tapToRetake': 'Tap to retake',
        'pleaseEnterNameFirst': 'Please enter a name first',
        'openingCameraFaceRotation': 'Opening camera for face rotation capture',
        'photosCapturedSuccessfully': 'photos captured successfully',
        'failedCaptureImages': 'Failed to capture images',
        'pleaseEnterName': 'Please enter a name',
        'pleaseCaptureRotationPhotos': 'Please capture face rotation photos first',
        'encryptingUploadingPhotos': 'Encrypting and uploading photos. Please wait.',
        'personAddedSuccessfully': 'Person added successfully with',
        'photos': 'photos',
        'failedAddPerson': 'Failed to add person',
        'errorAddingPerson': 'Error adding person, please try again',
        'nameFieldEnterPersonName': 'Name field, enter the person name',
        'photoSectionTapStart': 'Photo section. Tap to start face rotation capture. The camera will guide you to take 5 photos from different angles.',
        'addNewPersonButton': 'Add new person button, processing photos. Please wait.',
        'processingPhotos': 'Processing photos...',

        // Camera Screen
        'textReadingMode': 'Text Reading Mode',
        'colorDetectionMode': 'Color Detection Mode',
        'faceRecognitionMode': 'Face Recognition Mode',
        'unknownMode': 'Unknown mode',
        'newPhoto': 'New Photo',
        'extractedText': 'Extracted Text:',
        'detectedColor': 'Detected Color:',
        'recognized': 'Recognized:',
        'status': 'Status:',
        'unknownPerson': 'Unknown Person',
        'confidence': 'Confidence',
        'detectingColor': 'Detecting color...',
        'recognizingFace': 'Recognizing face...',
        'processingText': 'Processing text...',
        'noTextDetected': 'No text detected in the image',
        'theColorIs': 'The color is',
        'couldNotDetectColor': 'Could not detect color',
        'pleaseLoginFaceRecognition': 'Please login to use face recognition',
        'faceRecognized': 'Face recognized. This is',
        'faceDetectedNotRecognized': 'Face detected but not recognized. Unknown person',
        'errorRecognizingFace': 'Error recognizing face. Please try again',
        'faceRecognitionApiConnected': 'Face recognition API connected',
        'failedConnectFaceRecognition': 'Failed to connect to face recognition API',
        'colorDetectedAudio': 'Color detected and playing audio!',
        'faceProcessedAudio': 'Face processed and playing audio!',
        'textExtractedAudio': 'Text extracted and playing audio!',
        'faceRecognizedTitle': 'Face Recognized!',
        'unknownFace': 'Unknown Face',
        'similarity': 'Similarity',
        'notInDatabase': 'Not in database',
        'bestMatch': 'Best Match',
        'personNotFoundDatabase': 'Person not found in database',
        'close': 'Close',
        'done': 'Done',

        // ContactInfoPage
        'emergencyContacts': 'Emergency Contacts',
        'contactsCount': 'Contacts',
        'searchContacts': 'Search contacts...',
        'noContactsFound': 'No contacts found',
        'tryDifferentSearch': 'Try a different search term',
        'noContactsAdded': 'No contacts added yet',
        'tapBelowToAdd': 'Tap the button below to add your first contact',
        'deleteContact': 'Delete Contact',
        'areYouSureDelete': 'Are you sure you want to delete',
        'addVoiceContact': 'Add Voice Contact',
        'listening': 'Listening...',
        'updateContactName': 'Update contact name?',
        'whatsContactName': "What's the contact name?",
        'updatePhoneNumber': 'Update phone number?',
        'whatsPhoneNumber': "What's the phone number?",
        'processing': 'Processing...',
        'sayNewNameOrSame': 'Say the new name or "same" to keep it',
        'current': 'Current',
        'sayContactFullName': "Say the contact's full name",
        'sayNewPhoneOrSame': 'Say the new phone number or "same" to keep it',
        'exampleZeroFive': 'Example: "zero five one two three..."',
        'sayPhoneDigitByDigit': 'Say the phone number digit by digit',
        'cancelled': 'Cancelled',
        'alreadyOnEmergencyContacts': 'You are already on Emergency Contacts page',

        // CurrencyCameraScreen
        'currencyDetectionMode': 'Currency Detection Mode',
        'detectedCurrency': 'Detected Currency:',
        'recognizingCurrency': 'Recognizing currency...',

        // DeviceAlertsPage
        'deviceAndAlerts': 'Device & Alerts',
        'manageNotificationsDevices': 'Manage notifications & devices',
        'bluetoothDevice': 'Bluetooth Device',
        'enableAutomaticConnection': 'Enable automatic connection',
        'deviceAlertsTitle': 'Device Alerts',
        'receiveNotifications': 'Receive notifications',
        'information': 'Information',
        'bluetoothConnectionInfo': 'Bluetooth connection allows the app to automatically connect to your smart glass. Device alerts will notify you of important reminders!',
        'bluetoothEnabled': 'Bluetooth enabled',
        'bluetoothDisabled': 'Bluetooth disabled',
        'alertsEnabled': 'Alerts enabled',
        'alertsDisabled': 'Alerts disabled',
        'settingsSavedSuccessfully': 'Settings saved successfully',
        'failedToLoadSettings': 'Failed to load settings',
        'failedToSaveSettings': 'Failed to save settings',
      },
      'ar': {
        // Onboarding
        'welcomeToMunir': 'مرحبًا بك في منير',
        'smartAssistance': 'مساعدة ذكية من أجلك',
        'aiCompanion': 'رفيقك الذكي لحياة يومية أسهل.',
        'readTextRecognize': 'قراءة النصوص، التعرف على الوجوه، والحصول على ملاحظات فورية.',
        'tapToContinue': 'اضغط في أي مكان للمتابعة',
        
        // Welcome Screen
        'welcomeToJourney': 'مرحبًا بك في رحلتك الجديدة',
        'createAccount': 'إنشاء حساب',
        'login': 'تسجيل الدخول',
        
        // Login Screen
        'welcomeBack': 'مرحبًا بعودتك',
        'loginToContinue': 'سجّل الدخول لمتابعة رحلتك',
        'emailAddress': 'البريد الإلكتروني',
        'password': 'كلمة المرور',
        'rememberMe': 'تذكرني',
        'forgotPassword': 'نسيت كلمة المرور؟',
        'or': 'أو',
        'continueWithGoogle': 'المتابعة باستخدام Google',
        'dontHaveAccount': 'ليس لديك حساب؟ ',
        'signUp': 'إنشاء حساب',
        'logIn': 'تسجيل الدخول',
        
        // Signup Screen
        'joinUs': 'انضم إلينا وابدأ رحلتك',
        'name': 'الاسم',
        'mobileNumber': 'رقم الجوال (05XXXXXXXX)',
        'confirmPassword': 'تأكيد كلمة المرور',
        'passwordRequirements': 'متطلبات كلمة المرور:',
        'atLeast8Chars': '8 أحرف على الأقل',
        'oneUppercase': 'حرف كبير (A-Z)',
        'oneLowercase': 'حرف صغير (a-z)',
        'oneNumber': 'رقم (0-9)',
        'oneSpecialChar': 'رمز خاص',
        'passwordStrength': 'قوة كلمة المرور',
        'alreadyHaveAccount': 'لديك حساب بالفعل؟ ',
        
        // Email Verification
        'checkYourEmail': 'تحقق من بريدك الإلكتروني',
        'emailVerified': 'تم التحقق من البريد!',
        'redirectingToHome': 'جارٍ التوجيه للصفحة الرئيسية...',
        'weSentEmail': 'أرسلنا رسالة إلى',
        'important': 'مهم!',
        'checkSpam': 'تحقق من مجلد البريد المزعج!',
        'nextSteps': 'الخطوات التالية',
        'resendEmail': 'إعادة إرسال رسالة التحقق',
        'resendIn': 'إعادة الإرسال خلال',
        'seconds': 'ثانية',
        'backToLogin': 'العودة لتسجيل الدخول',

        // Settings Page
        'settings': 'الإعدادات',
        'managePreferences': 'إدارة تفضيلاتك',
        'accountInfo': 'معلومات الحساب',
        'editPersonalInfo': 'تعديل المعلومات الشخصية أو حذف حسابك',
        'deviceAlerts': 'الجهاز والتنبيهات',
        'setupConnections': 'إعداد الاتصالات والإشعارات',
        'changePassword': 'تغيير كلمة المرور',
        'managePassword': 'إدارة كلمة المرور',
        'logout': 'تسجيل الخروج',
        'signOut': 'الخروج من حسابك',
        'logoutConfirm': 'هل أنت متأكد من تسجيل الخروج من حسابك؟',
        'confirm': 'تأكيد',
        'cancel': 'إلغاء',
        'logoutSuccess': 'تم تسجيل الخروج بنجاح',
        'logoutFailed': 'فشل تسجيل الخروج. حاول مرة أخرى',
        'goingBack': 'العودة',
        'home': 'الرئيسية',
        'reminders': 'التذكيرات',
        'contacts': 'جهات الاتصال',
        'emergency': 'طوارئ',
        'alreadyOnSettings': 'أنت بالفعل في صفحة الإعدادات',

        // HomePage
        'faceRecognition': 'التعرف على الوجوه',
        'identifyPeopleInstantly': 'تعرّف على الأشخاص فوراً',
        'textReading': 'قراءة النصوص',
        'readTextAloud': 'قراءة النص بصوت عالٍ',
        'currencyRecognition': 'التعرف على العملات',
        'recognizeCurrencyInstantly': 'تعرّف على العملة فوراً',
        'colorIdentification': 'تحديد الألوان',
        'identifyColorsAround': 'تعرّف على الألوان من حولك',
        'profile': 'الملف الشخصي',
        'managePersonalInfo': 'إدارة معلوماتك الشخصية',
        'alreadyOnHomepage': 'أنت بالفعل في الصفحة الرئيسية',

        // Account Info Page
        'manageAccountSettings': 'إدارة إعدادات حسابك',
        'personalInformation': 'المعلومات الشخصية',
        'editAccountInfo': 'تعديل معلومات حسابك',
        'deleteMyAccount': 'حذف حسابي',
        'permanentlyDelete': 'حذف حسابك نهائياً',
        'deleteAccount': 'حذف الحساب',
        'deleteAccountConfirm': 'هل أنت متأكد من حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه',
        'deletionCancelled': 'تم إلغاء الحذف',
        'noUserSignedIn': 'لا يوجد مستخدم مسجل حالياً',
        'emailNotFound': 'البريد غير موجود. من فضلك سجّل الدخول مرة أخرى',
        'confirmYourPassword': 'أكد كلمة المرور',
        'enterPasswordToContinue': 'من فضلك ادخل كلمة المرور للمتابعة.',
        'enterYourPassword': 'ادخل كلمة المرور',
        'passwordRequired': 'كلمة المرور مطلوبة',
        'invalidPassword': 'كلمة مرور غير صحيحة. حاول مرة أخرى',
        'pleaseWait': 'انتظر...',
        'reauthCancelled': 'تم إلغاء إعادة المصادقة',
        'networkTimeout': 'انتهت مهلة الشبكة أثناء التحقق من كلمة المرور',
        'authError': 'خطأ في المصادقة',
        'unexpectedError': 'خطأ غير متوقع أثناء التحقق',
        'accountDeletedSuccess': 'تم حذف الحساب بنجاح',
        'redirectingToSignup': 'تم حذف الحساب بنجاح. جاري التوجيه لإنشاء حساب',

        // AddPersonPage
        'addNewPerson': 'إضافة شخص جديد',
        'enterName': 'ادخل الاسم',
        'photo': 'الصورة',
        'tapToCaptureFaceRotation': 'اضغط لالتقاط دوران الوجه',
        'frontLeftRightUpDown': 'أمام، يسار، يمين، أعلى، أسفل',
        'rotationPhotosCaptured': 'تم التقاط صور دوران',
        'tapToRetake': 'اضغط لإعادة الالتقاط',
        'pleaseEnterNameFirst': 'من فضلك ادخل الاسم أولاً',
        'openingCameraFaceRotation': 'فتح الكاميرا لالتقاط دوران الوجه',
        'photosCapturedSuccessfully': 'تم التقاط الصور بنجاح',
        'failedCaptureImages': 'فشل التقاط الصور',
        'pleaseEnterName': 'من فضلك ادخل اسماً',
        'pleaseCaptureRotationPhotos': 'من فضلك التقط صور دوران الوجه أولاً',
        'encryptingUploadingPhotos': 'تشفير ورفع الصور. انتظر من فضلك',
        'personAddedSuccessfully': 'تمت إضافة الشخص بنجاح مع',
        'photos': 'صور',
        'failedAddPerson': 'فشلت إضافة الشخص',
        'errorAddingPerson': 'خطأ في إضافة الشخص، حاول مرة أخرى',
        'nameFieldEnterPersonName': 'حقل الاسم، ادخل اسم الشخص',
        'photoSectionTapStart': 'قسم الصورة. اضغط لبدء التقاط دوران الوجه. الكاميرا ستوجهك لالتقاط 5 صور من زوايا مختلفة',
        'addNewPersonButton': 'زر إضافة شخص جديد، معالجة الصور. انتظر من فضلك',
        'processingPhotos': 'معالجة الصور...',

        // Camera Screen
        'textReadingMode': 'وضع قراءة النصوص',
        'colorDetectionMode': 'وضع اكتشاف الألوان',
        'faceRecognitionMode': 'وضع التعرف على الوجوه',
        'unknownMode': 'وضع غير معروف',
        'newPhoto': 'صورة جديدة',
        'extractedText': 'النص المستخرج:',
        'detectedColor': 'اللون المكتشف:',
        'recognized': 'تم التعرف:',
        'status': 'الحالة:',
        'unknownPerson': 'شخص غير معروف',
        'confidence': 'الثقة',
        'detectingColor': 'اكتشاف اللون...',
        'recognizingFace': 'التعرف على الوجه...',
        'processingText': 'معالجة النص...',
        'noTextDetected': 'لم يتم اكتشاف نص في الصورة',
        'theColorIs': 'اللون هو',
        'couldNotDetectColor': 'لم نتمكن من اكتشاف اللون',
        'pleaseLoginFaceRecognition': 'من فضلك سجّل الدخول لاستخدام التعرف على الوجوه',
        'faceRecognized': 'تم التعرف على الوجه. هذا',
        'faceDetectedNotRecognized': 'تم اكتشاف وجه لكن لم يتم التعرف عليه. شخص غير معروف',
        'errorRecognizingFace': 'خطأ في التعرف على الوجه. حاول مرة أخرى',
        'faceRecognitionApiConnected': 'تم الاتصال بواجهة التعرف على الوجوه',
        'failedConnectFaceRecognition': 'فشل الاتصال بواجهة التعرف على الوجوه',
        'colorDetectedAudio': 'تم اكتشاف اللون وتشغيل الصوت!',
        'faceProcessedAudio': 'تمت معالجة الوجه وتشغيل الصوت!',
        'textExtractedAudio': 'تم استخراج النص وتشغيل الصوت!',
        'faceRecognizedTitle': 'تم التعرف على الوجه!',
        'unknownFace': 'وجه غير معروف',
        'similarity': 'التشابه',
        'notInDatabase': 'غير موجود في قاعدة البيانات',
        'bestMatch': 'أفضل تطابق',
        'personNotFoundDatabase': 'الشخص غير موجود في قاعدة البيانات',
        'close': 'إغلاق',
        'done': 'تم',

        // ContactInfoPage
        'emergencyContacts': 'جهات الاتصال الطارئة',
        'contactsCount': 'جهات اتصال',
        'searchContacts': 'البحث عن جهات الاتصال...',
        'noContactsFound': 'لم يتم العثور على جهات اتصال',
        'tryDifferentSearch': 'جرب مصطلح بحث مختلف',
        'noContactsAdded': 'لم تتم إضافة جهات اتصال بعد',
        'tapBelowToAdd': 'اضغط على الزر أدناه لإضافة أول جهة اتصال',
        'deleteContact': 'حذف جهة الاتصال',
        'areYouSureDelete': 'هل أنت متأكد من حذف',
        'addVoiceContact': 'إضافة جهة اتصال صوتية',
        'listening': 'جاري الاستماع...',
        'updateContactName': 'تحديث اسم جهة الاتصال؟',
        'whatsContactName': 'ما هو اسم جهة الاتصال؟',
        'updatePhoneNumber': 'تحديث رقم الهاتف؟',
        'whatsPhoneNumber': 'ما هو رقم الهاتف؟',
        'processing': 'جاري المعالجة...',
        'sayNewNameOrSame': 'قل الاسم الجديد أو "نفسه" للإبقاء عليه',
        'current': 'الحالي',
        'sayContactFullName': 'قل الاسم الكامل لجهة الاتصال',
        'sayNewPhoneOrSame': 'قل رقم الهاتف الجديد أو "نفسه" للإبقاء عليه',
        'exampleZeroFive': 'مثال: "صفر خمسة واحد اثنين ثلاثة..."',
        'sayPhoneDigitByDigit': 'قل رقم الهاتف رقماً برقم',
        'cancelled': 'تم الإلغاء',
        'alreadyOnEmergencyContacts': 'أنت بالفعل في صفحة جهات الاتصال الطارئة',

        // CurrencyCameraScreen
        'currencyDetectionMode': 'وضع اكتشاف العملات',
        'detectedCurrency': 'العملة المكتشفة:',
        'recognizingCurrency': 'التعرف على العملة...',

        // DeviceAlertsPage
        'deviceAndAlerts': 'الجهاز والتنبيهات',
        'manageNotificationsDevices': 'إدارة الإشعارات والأجهزة',
        'bluetoothDevice': 'جهاز البلوتوث',
        'enableAutomaticConnection': 'تفعيل الاتصال التلقائي',
        'deviceAlertsTitle': 'تنبيهات الجهاز',
        'receiveNotifications': 'استقبال الإشعارات',
        'information': 'معلومات',
        'bluetoothConnectionInfo': 'اتصال البلوتوث يسمح للتطبيق بالاتصال تلقائياً بنظارتك الذكية. تنبيهات الجهاز ستخطرك بالتذكيرات المهمة!',
        'bluetoothEnabled': 'تم تفعيل البلوتوث',
        'bluetoothDisabled': 'تم تعطيل البلوتوث',
        'alertsEnabled': 'تم تفعيل التنبيهات',
        'alertsDisabled': 'تم تعطيل التنبيهات',
        'settingsSavedSuccessfully': 'تم حفظ الإعدادات بنجاح',
        'failedToLoadSettings': 'فشل تحميل الإعدادات',
        'failedToSaveSettings': 'فشل حفظ الإعدادات',
      },
    };

    return translations[_languageCode]?[key] ?? key;
  }
}